package com.habitforge.forge.service;
import com.habitforge.forge.dto.*; import com.habitforge.forge.entity.*; import com.habitforge.forge.exception.*; import com.habitforge.forge.repository.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class HabitService {
 private final HabitRepository habitRepository; private final CompletionLogRepository completionRepository; private final StreakService streakService;
    private final StreakRepository streakRepository;
 public HabitService(HabitRepository h,CompletionLogRepository c,StreakService s,StreakRepository sr){habitRepository=h;completionRepository=c;streakService=s;streakRepository=sr;}
 @Transactional public HabitResponse create(HabitRequest r){Habit h=new Habit();apply(h,r);return toResponse(habitRepository.save(h));}
 @Transactional(readOnly=true) public Page<HabitResponse> list(boolean activeOnly,Pageable p){Page<Habit> page=activeOnly?habitRepository.findByActive(true,p):habitRepository.findAll(p);return page.map(this::toResponse);}
 @Transactional(readOnly=true) public HabitResponse one(Long id){return toResponse(find(id));}
 @Transactional public HabitResponse update(Long id,HabitRequest r){Habit h=find(id);apply(h,r);return toResponse(habitRepository.save(h));}
 @Transactional public void delete(Long id){find(id); streakRepository.deleteByHabitId(id); completionRepository.deleteByHabitId(id); habitRepository.deleteById(id);}
 @Transactional public CompletionResponse checkIn(Long id,CompletionRequest r){Habit h=find(id);LocalDate date=r.completedDate();if(date.isAfter(LocalDate.now()))throw new IllegalArgumentException("Completion date cannot be in the future");if(completionRepository.existsByHabitIdAndCompletedDate(id,date))throw new ConflictException("Habit is already completed for "+date);CompletionLog l=new CompletionLog();l.setHabit(h);l.setCompletedDate(date);l.setNote(r.note());CompletionLog saved=completionRepository.save(l);streakService.refresh(h);return new CompletionResponse(saved.getId(),id,saved.getCompletedDate(),saved.getNote(),saved.getCreatedAt());}
 @Transactional(readOnly=true) public List<CompletionResponse> logs(Long id){find(id);return completionRepository.findByHabitIdOrderByCompletedDateAsc(id).stream().map(l->new CompletionResponse(l.getId(),id,l.getCompletedDate(),l.getNote(),l.getCreatedAt())).toList();}
 @Transactional public StreakResponse streak(Long id){Habit h=find(id);Streak s=streakService.refresh(h);return new StreakResponse(id,h.getFrequency(),s.getCurrentStreak(),s.getBestStreak(),s.getLastCompletedDate(),s.getCurrentStreak()>0);}
 @Transactional(readOnly=true) public CalendarResponse calendar(Long id,int year,int month){find(id);YearMonth ym=YearMonth.of(year,month);List<LocalDate>d=completionRepository.findByHabitIdAndCompletedDateBetweenOrderByCompletedDateAsc(id,ym.atDay(1),ym.atEndOfMonth()).stream().map(CompletionLog::getCompletedDate).toList();return new CalendarResponse(id,year,month,d);}
 private Habit find(Long id){return habitRepository.findById(id).orElseThrow(()->new NotFoundException("Habit not found: "+id));}
 private void apply(Habit h,HabitRequest r){h.setName(r.name().trim());h.setDescription(r.description());h.setFrequency(r.frequency());h.setRemindersEnabled(r.remindersEnabled());h.setReminderTime(r.reminderTime());}
 private HabitResponse toResponse(Habit h){List<CompletionLog> logs=completionRepository.findByHabitIdOrderByCompletedDateAsc(h.getId());int current=streakService.calculateCurrent(logs,h.getFrequency(),LocalDate.now());int best=streakService.calculateBest(logs,h.getFrequency());LocalDate last=logs.isEmpty()?null:logs.get(logs.size()-1).getCompletedDate();return new HabitResponse(h.getId(),h.getName(),h.getDescription(),h.getFrequency(),h.isActive(),h.isRemindersEnabled(),h.getReminderTime(),current,best,last,h.getCreatedAt(),h.getUpdatedAt());}
}
